apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-http-server
  name: test-http-server
spec:
  containers:
  - image: nginx
    name: test-http-server
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
